language: go
go:
  - master
os:
  - osx
sudo: false
install: true
env:
  - GO111MODULE=on
script:
  - go get -u github.com/haya14busa/goverage
  - go get -u github.com/schrej/godacov
  - go build
  - go test
  - goverage -v -coverprofile=coverage.out ./...

after_success:
  - godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT
