language: go
go:
  - master
os:
  - osx
sudo: false
install: true
env:
  - GO111MODULE=on
  
script:
  - go get -u github.com/haya14busa/goverage
  - go get -u github.com/schrej/godacov
  - go build
  - go test -v -race ./...
  - goverage -v -coverprofile=coverage.txt ./...

after_success:
  - godacov -t $CODACY_TOKEN -r ./coverage.txt -c $TRAVIS_COMMIT
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Build failed" 